// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIz453HO5eg3Qeh1kHcNWvWU9W5U0--Ks',
    appId: '1:1086035113052:web:49951c0001f7455fc26299',
    messagingSenderId: '1086035113052',
    projectId: 'sample1-938dc',
    authDomain: 'sample1-938dc.firebaseapp.com',
    storageBucket: 'sample1-938dc.appspot.com',
    measurementId: 'G-BN5W18Q3T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKhlk0jxgzPpG-QEhnw15TvONHavn3wug',
    appId: '1:1086035113052:android:de0b1d6a5e57bb5bc26299',
    messagingSenderId: '1086035113052',
    projectId: 'sample1-938dc',
    storageBucket: 'sample1-938dc.appspot.com',
  );
}
